# Generated by Django 3.2.20 on 2025-05-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('acero_quirurgico', 'Acero Quirúrgico'), ('acero_blanco', 'Acero Blanco'), ('acero_dorado', 'Acero Dorado'), ('plata_925', 'Plata 925'), ('oro_18k', 'Oro 18k')], default='acero_quirurgico', max_length=50),
        ),
    ]
