# Generated by Django 5.2.1 on 2025-05-24 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0009_product_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta de crédito'), ('pendiente', 'Pendiente de pago')], default='pendiente', max_length=50)),
                ('pagado', models.BooleanField(default=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
