# Generated by Django 3.2.20 on 2025-05-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='tipo_talle',
            field=models.CharField(blank=True, choices=[('anillo', 'Anillo'), ('pulsera', 'Pulsera'), ('collar', 'Collar'), ('aro', 'Aro'), ('dije', 'Dije')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
